//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Common.rc
//
#define IDR_MAINFRAME                   128
#define IDD_SENSOR_DLG                  4000
#define IDC_SENSOR                      4001
#define IDD_DATALIST_DLG                4001
#define IDC_SENSOR_GRP                  4002
#define IDD_STATEMAP_DLG                4002
#define IDC_SENSOR_SHOW_SCANLINE        4003
#define IDC_SENSOR_ENABLE               4004
#define IDC_SENSOR_PARAM_GRP            4005
#define IDC_SENSOR_TYPE                 4006
#define IDC_SENSOR_TYPE_STATIC          4007
#define IDC_SENSOR_MAX_DIS_STATIC       4008
#define IDC_SENSOR_MAX_DIS              4009
#define IDC_SENSOR_MAX_THETA_STATIC     4010
#define IDC_SENSOR_MAX_THETA            4011
#define IDC_SENSOR_MAX_PHI_STATIC       4012
#define IDC_SENSOR_MAX_PHI              4013
#define IDC_SENSOR_DIS_VAR_STATIC       4014
#define IDC_SENSOR_DIS_VAR              4015
#define IDC_SENSOR_THETA_VAR_STATIC     4016
#define IDC_SENSOR_THETA_VAR            4017
#define IDC_SENSOR_PHI_VAR_STATIC       4018
#define IDC_SENSOR_PHI_VAR              4019
#define IDC_SENSOR_PRO_DET_STATIC       4020
#define IDC_SENSOR_PRO_DET              4021
#define IDC_SENSOR_SHOW_TRACK           4022
#define IDC_SENSOR_TARGET_ID            4023
#define IDC_SENSOR_TARGET_ID_STATIC     4024
#define IDC_SENSOR_TARGET_COLOR         4025
#define IDC_SENSOR_TARGET_COLOR_STATIC  4026
#define IDC_DATALIST_TARGET_ID_STATIC   4027
#define IDC_STATEMAP_BACKGROUND         4027
#define IDC_DATALIST_PARAM_GRP          4028
#define IDC_STATEMAP_BACKGROUND_STATIC  4028
#define IDC_DATALIST_TARGET_ID          4029
#define IDC_STATEMAP_PLANE_TYPE         4029
#define IDC_DATALIST_TARGET_COLOR_STATIC 4030
#define IDC_STATEMAP_PLANE_TYPE_STATIC  4030
#define IDC_DATALIST_TARGET_COLOR       4031
#define IDC_STATEMAP_PLANE_COLOR        4031
#define IDC_DATALIST_GRP                4032
#define IDC_STATEMAP_PLANE_COLOR_STATIC 4032
#define IDC_DATALIST                    4033
#define IDC_STATEMAP_PLANE_TYPE2        4033
#define IDC_STATEMAP_PLANE_ID           4033
#define IDC_STATEMAP                    4034
#define IDC_STATEMAP_GRP                4035
#define IDC_STATEMAP_SHOW_THETA_RANGE   4036
#define IDC_STATEMAP_SHOW_TRACK         4037
#define IDC_STATEMAP_TARGET_ID_STATIC   4038
#define IDC_STATEMAP_TARGET_ID          4039
#define IDC_STATEMAP_TARGET_TYPE_STATIC 4040
#define IDC_STATEMAP_TARGET_TYPE        4041
#define IDC_STATEMAP_TARGET_COLOR       4042
#define IDC_STATEMAP_TARGET_COLOR_STATIC 4043
#define IDC_STATEMAP_PARAM_GRP          4044
#define IDC_STATEMAP_PLANE_ID_STATIC    4045
#define IDC_STATEMAP_MISS_ID            4046
#define IDC_STATEMAP_MISS_ID_STATIC     4047
#define IDC_STATEMAP_MISS_TYPE          4048
#define IDC_STATEMAP_MISS_TYPE_STATIC   4049
#define IDC_STATEMAP_MISS_COLOR         4050
#define IDC_STATEMAP_MISS_COLOR_STATIC  4051
#define IDC_STATEMAP_BACKGROUND2        4052
#define IDC_STATEMAP_EXPLOSION_TYPE     4052
#define IDC_STATEMAP_EXPLOSION_TYPE_STATIC 4053

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        4003
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         4045
#define _APS_NEXT_SYMED_VALUE           4000
#endif
#endif
