//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DataCenter.rc
//
#define IDD_DATACENTER_DLG              102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDC_DC_TARGET_ADD               1000
#define IDC_MATLAB_DLG_BUTTON           1001
#define IDC_MATLAB_DLG_STATE_MAP        1002
#define IDC_STATE_MAP_DLG_BUTTON        1002
#define IDC_GLOBAL_WILD_VALUE           1003
#define IDC_GLOBAL_DELAY                1004
#define IDC_SUB_PANEL_GRP               1005
#define IDC_DC_EVAL                     1006
#define IDC_DC_EVAL_ADD                 1006
#define IDC_EXT_DATA_LOAD_BUTTON        1007
#define IDC_CONFIG_GRP                  1008
#define IDC_CONFIG_LOAD                 1009
#define IDC_CONFIG_SAVE                 1010
#define IDC_EDIT1                       1013
#define IDC_EXT_DATA_PATH               1013
#define IDC_DC_SENSOR_ENABLE            4004
#define IDC_DC_SENSOR_PARAM_GRP         4005
#define IDC_DC_PLANE_PARAM_GRP          4006
#define IDC_DC_TARGET_PARAM_GRP         4007
#define IDC_DC_EVAL_PARAM_GRP           4007
#define IDC_DC_SENSOR_MAX_DIS_STATIC    4008
#define IDC_DC_SENSOR_MAX_DIS           4009
#define IDC_DC_SENSOR_MAX_THETA_STATIC  4010
#define IDC_DC_SENSOR_MAX_THETA         4011
#define IDC_DC_SENSOR_MAX_PHI_STATIC    4012
#define IDC_DC_SENSOR_MAX_PHI           4013
#define IDC_DC_SENSOR_DIS_VAR_STATIC    4014
#define IDC_DC_SENSOR_DIS_VAR           4015
#define IDC_DC_SENSOR_THETA_VAR_STATIC  4016
#define IDC_DC_SENSOR_THETA_VAR         4017
#define IDC_DC_SENSOR_PHI_VAR_STATIC    4018
#define IDC_DC_SENSOR_PHI_VAR           4019
#define IDC_DC_SENSOR_PRO_DET_STATIC    4020
#define IDC_DC_SENSOR_PRO_DET           4021
#define IDC_DC_PLANE_ID_SET_STATIC      4022
#define IDC_DC_SENSOR_ID                4023
#define IDC_DC_SENSOR_ID_STATIC         4024
#define IDC_DC_PLANE_ID                 4025
#define IDC_DC_PLANE_ID_STATIC          4026
#define IDC_DC_PLANE_COLOR              4027
#define IDC_DC_PLANE_COLOR_STATIC       4028
#define IDC_DC_PLANE_ID_SET             4029
#define IDC_DC_PLANE_POS_X_STATIC       4030
#define IDC_DC_PLANE_POS_X              4031
#define IDC_DC_PLANE_MOTION             4032
#define IDC_DC_PLANE_MOTION_STATIC      4033
#define IDC_DC_PLANE_POS_Y_STATIC       4034
#define IDC_DC_PLANE_POS_Y              4035
#define IDC_DC_PLANE_POS_Z_STATIC       4036
#define IDC_DC_PLANE_POS_Z              4037
#define IDC_DC_PLANE_VEL_X_STATIC       4038
#define IDC_DC_PLANE_VEL_X              4039
#define IDC_DC_PLANE_VEL_Y_STATIC       4040
#define IDC_DC_PLANE_VEL_Y              4041
#define IDC_DC_PLANE_VEL_Z_STATIC       4042
#define IDC_DC_PLANE_VEL_Z              4043
#define IDC_DC_TARGET_ID                4044
#define IDC_DC_EVAL_ID                  4044
#define IDC_DC_TARGET_ID_STATIC         4045
#define IDC_DC_EVAL_ID_STATIC           4045
#define IDC_DC_TARGET_COLOR             4046
#define IDC_DC_EXT_DATA_ENABLE          4046
#define IDC_DC_TARGET_COLOR_STATIC      4047
#define IDC_DC_TARGET_ID_SET_STATIC     4048
#define IDC_DC_EVAL_NAME_STATIC         4048
#define IDC_DC_TARGET_ID_SET            4049
#define IDC_DC_EVAL_NAME                4049
#define IDC_DC_PLANE_ACC_X_STATIC       4050
#define IDC_DC_PLANE_ACC_X              4051
#define IDC_DC_PLANE_ACC_Y_STATIC       4052
#define IDC_DC_PLANE_ACC_Y              4053
#define IDC_DC_TARGET_POS_X_STATIC      4054
#define IDC_DC_EVAL_PLANE_TRUE_STATIC   4054
#define IDC_DC_TARGET_POS_X             4055
#define IDC_DC_EVAL_PLANE_TRUE          4055
#define IDC_DC_PLANE_ACC_Z_STATIC       4056
#define IDC_DC_PLANE_ACC_Z              4057
#define IDC_DC_PLANE_R_STATIC           4058
#define IDC_DC_PLANE_PAL_STATIC         4058
#define IDC_DC_PLANE_R                  4059
#define IDC_DC_PLANE_PAL                4059
#define IDC_DC_TARGET_MOTION            4060
#define IDC_DC_EVAL_DLL_STATIC          4060
#define IDC_DC_TARGET_MOTION_STATIC     4061
#define IDC_DC_EVAL_DLL                 4061
#define IDC_DC_TARGET_POS_Y_STATIC      4062
#define IDC_DC_EVAL_TARGET_TRUE_STATIC  4062
#define IDC_DC_TARGET_POS_Y             4063
#define IDC_DC_EVAL_TARGET_TRUE         4063
#define IDC_DC_TARGET_POS_Z_STATIC      4064
#define IDC_DC_TARGET_NOISE_STATIC      4064
#define IDC_DC_TARGET_POS_Z             4065
#define IDC_DC_TARGET_NOISE             4065
#define IDC_DC_TARGET_VEL_X_STATIC      4066
#define IDC_DC_EVAL_FUSION_STATIC       4066
#define IDC_DC_TARGET_VEL_X             4067
#define IDC_DC_EVAL_FUSION              4067
#define IDC_DC_TARGET_VEL_Y_STATIC      4068
#define IDC_DC_EVAL_FILTER_STATIC       4068
#define IDC_DC_TARGET_VEL_Y             4069
#define IDC_DC_EVAL_FILTER              4069
#define IDC_DC_TARGET_VEL_Z_STATIC      4070
#define IDC_DC_TARGET_VEL_Z             4071
#define IDC_DC_TARGET_ACC_X_STATIC      4072
#define IDC_DC_TARGET_ACC_X             4073
#define IDC_DC_TARGET_ACC_Y_STATIC      4074
#define IDC_DC_TARGET_ACC_Y             4075
#define IDC_DC_TARGET_ACC_Z_STATIC      4076
#define IDC_DC_TARGET_ACC_Z             4077
#define IDC_DC_TARGET_R_STATIC          4078
#define IDC_DC_TARGET_R                 4079
#define IDC_DC_PLANE_TYPE               4080
#define IDC_DC_PLANE_TYPE_STATIC        4081
#define IDC_DC_TARGET_TYPE              4082
#define IDC_DC_TARGET_TYPE_STATIC       4083
#define IDC_DC_GLOBAL_PARAM_GRP         4084
#define IDC_DC_GLOBAL_CYCLE_STATIC      4085
#define IDC_DC_GLOBAL_CYCLE             4086
#define IDC_DC_GLOBAL_FUSION_ALGO_STATIC 4087
#define IDC_DC_STATE_MAP_PARAM_GRP      4088
#define IDC_DC_GLOBAL_FUSION_ALGO       4089
#define IDC_DC_GLOBAL_NOISE_STATIC      4090
#define IDC_DC_GLOBAL_NOISE             4091
#define IDC_DC_GLOBAL_WILD_STATIC       4092
#define IDC_DC_PLANE_RADIUS_STATIC      4092
#define IDC_DC_GLOBAL_WILD              4093
#define IDC_DC_PLANE_RADIUS             4093
#define IDC_DC_GLOBAL_DELAY_STATIC      4094
#define IDC_DC_EXT_DATA_GRP             4094
#define IDC_DC_GLOBAL_DELAY             4095
#define IDC_DC_GLOBAL_START_TIME_STATIC 4096
#define IDC_DC_GLOBAL_START_TIME        4097
#define IDC_DC_GLOBAL_END_TIME_STATIC   4098
#define IDC_DC_GLOBAL_END_TIME          4099
#define IDC_DC_GLOBAL_NAVI_ALGO_STATIC  4100
#define IDC_DC_GLOBAL_NAVI_ALGO         4101
#define IDC_DC_GLOBAL_ROUNDS_STATIC     4102
#define IDC_DC_GLOBAL_ROUNDS            4103
#define IDC_DC_STATE_MAP_BKG            4104
#define IDC_DC_STATE_MAP_BKG_STATIC     4105
#define IDC_DC_STATE_MAP_MAX_X_STATIC   4106
#define IDC_DC_SENSOR_PRO_DET2          4107
#define IDC_DC_STATE_MAP_MAX_X          4107
#define IDC_DC_STATE_MAP_MAX_Y_STATIC   4108
#define IDC_DC_STATE_MAP_MAX_Y          4109

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1014
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
